checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: './run_tests.sh --coverage-clover=coverage-file --coverage-filter=src'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'
